foundationpose_stereo_tracker_fast_node:
  ros__parameters:
    left_image_topic: /left/image_raw
    right_image_topic: /right/image_raw
    image_reliability: 1
    sync_queue_size: 10
    max_sync_interval_sec: 0.07

    stereo_model_type: FAST_FOUNDATION_STEREO
    stereo_engine_file_path:
      - /home/bit/model/ffs/20-30-48/320-512/feature_runner_fp16_thor.engine
      - /home/bit/model/ffs/20-30-48/320-512/post_runner_fp16_thor.engine
    model_input_width: 512
    model_input_height: 320
    min_depth_meters: 0.1
    max_depth_meters: 100.0
    caminfo_path: /home/bit/ffs+fp+sam/ffs/jrnew.txt

    refiner_engine_path: /home/bit/ffs+fp+sam/fp/models/refiner_hwc_dynamic_fp16_thor.engine
    scorer_engine_path: /home/bit/ffs+fp+sam/fp/models/scorer_hwc_dynamic_fp16_thor.engine
    mesh_path: /home/bit/dataset/jrnew-blue/mesh/textured_mesh.obj
    object_name: blue carton

    mask_image_path: ""
    mask_image_directory: /home/bit/ffs+fp+sam/Grounded-Segment-Anything/ros2_outputs/first_mask
    mask_image_name: first_mask.png
    resize_mask_to_input: false
    mask_poll_interval_ms: 200

    pose_topic: /foundationpose/pose
    pose_frame_id: camera_color_optical_frame
    visualization_topic: /foundationpose/visualization
    visualization_window_name: foundationpose_visualization
    publish_visualization: false
    show_visualization_window: true

    fx: 736.0934
    fy: 736.6856
    cx: 989.8375
    cy: 551.6085
    max_input_image_height: 1080
    max_input_image_width: 1920
    register_refine_iterations: 5
    track_refine_iterations: 2
