rgbd_sequence_publisher_node:
  ros__parameters:
    sequence_dir: /home/hc/weizi/fp/src/foundationpose_cpp/test_data/mustard0
    rgb_subdir: rgb
    depth_subdir: depth

    rgb_topic: /camera/color/image_raw
    depth_topic: /camera/depth/image_raw
    rgb_camera_info_topic: /camera/color/camera_info
    depth_camera_info_topic: /camera/depth/camera_info
    frame_id: camera_color_optical_frame
    camera_info_path: /home/hc/weizi/fp/src/foundationpose_cpp/test_data/mustard0/cam_K.txt

    fps: 1.0
    loop: true
    use_filename_timestamp: false
    publish_camera_info: true
    use_sensor_data_qos: false
