<?xml version="1.0"?>
<package format="3">
  <name>sim_stereo_cpp</name>
  <version>0.0.1</version>
  <description>Real-time stereo mesh renderer and ROS2 image publisher in C++.</description>

  <maintainer email="hc@example.com">hc</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>sensor_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>ament_index_python</depend>
  <depend>launch</depend>
  <depend>launch_ros</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
